# Generated by Django 2.2 on 2019-04-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0002_auto_20190426_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='visits',
            new_name='hits',
        ),
    ]
